import type { TeamMember, Desafio } from './types';

export const teamMembers: TeamMember[] = [
  {
    id: 'insaurralde-mariano',
    firstName: 'Mariano',
    lastName: 'Insaurralde',
    fullName: 'Insaurralde, Mariano',
    role: 'Líder de Proyecto & Arquitecto de Software',
    bio: 'Apasionado por la arquitectura de sistemas escalables y la gestión ágil de proyectos. Combina habilidades técnicas con visión estratégica para liderar equipos multidisciplinarios.',
    skills: ['Arquitectura de Software', 'Gestión Ágil', 'Liderazgo', 'TypeScript', 'Sistemas Distribuidos'],
    avatarPath: '/assets/avatars/insaurralde_mariano.webp',
  },
  {
    id: 'fernandez-matias',
    firstName: 'Matias',
    lastName: 'Fernandez',
    fullName: 'Fernandez, Matias',
    role: 'Desarrollador Full Stack',
    bio: 'Especialista en desarrollo web moderno con foco en rendimiento y experiencia de usuario. Disfruta resolver problemas complejos con soluciones elegantes y mantenibles.',
    skills: ['React', 'Node.js', 'Bases de Datos', 'APIs REST', 'DevOps'],
    avatarPath: '/assets/avatars/fernandez_matias.webp',
  },
  {
    id: 'philippe-maurel',
    firstName: 'Maurel',
    lastName: 'Philippe',
    fullName: 'Philippe, Maurel',
    role: 'Analista de Sistemas & UX',
    bio: 'Bridging the gap entre los requerimientos del negocio y la implementación técnica. Enfocado en la usabilidad y la experiencia del usuario como eje central del diseño.',
    skills: ['Análisis de Sistemas', 'UX/UI', 'Modelado de Procesos', 'Documentación', 'Testing'],
    avatarPath: '/assets/avatars/philippe_maurel.webp',
  },
  {
    id: 'sanchez-franco',
    firstName: 'Franco',
    lastName: 'Sanchez',
    fullName: 'Sanchez, Franco',
    role: 'Especialista en Seguridad & Backend',
    bio: 'Orientado a la seguridad informática y el desarrollo backend robusto. Garantiza la integridad y confiabilidad de los sistemas bajo cualquier condición.',
    skills: ['Ciberseguridad', 'Backend', 'Bases de Datos', 'Redes', 'Análisis de Riesgos'],
    avatarPath: '/assets/avatars/sanchez_franco.webp',
  },
  {
    id: 'acosta-sandra',
    firstName: 'Sandra',
    lastName: 'Acosta',
    fullName: 'Acosta, Sandra',
    role: 'Gestión de Calidad & Scrum Master',
    bio: 'Asegura que cada entrega cumpla con los más altos estándares de calidad. Facilita la comunicación y la mejora continua dentro del equipo usando metodologías ágiles.',
    skills: ['QA Testing', 'Scrum', 'Kanban', 'Gestión de Calidad', 'Documentación Técnica'],
    avatarPath: '/assets/avatars/acosta_sandra.webp',
  },
];

export const desafios: Desafio[] = [
  {
    slug: 'd3',
    code: 'D3',
    title: 'Desafío 3: [Título por completar]',
    problem: 'Descripción del problema o situación que motivó este desafío. Este apartado detallará el contexto, el alcance y los actores involucrados en la problemática abordada.',
    solution: 'Descripción de la solución propuesta por el equipo. Se detallarán las estrategias, métodos y tecnologías seleccionadas para resolver el problema planteado.',
    tools: ['Herramienta 1', 'Herramienta 2', 'Herramienta 3'],
    evidences: [
      { label: 'Presentación del equipo', href: '#', type: 'presentation' },
      { label: 'Informe técnico', href: '#', type: 'document' },
    ],
    reflection: 'Reflexión del equipo sobre los aprendizajes obtenidos, competencias desarrolladas y cómo este desafío impactó en nuestro crecimiento profesional y grupal.',
  },
  {
    slug: 'd4',
    code: 'D4',
    title: 'Desafío 4: [Título por completar]',
    problem: 'Descripción del problema o situación que motivó este desafío. Este apartado detallará el contexto, el alcance y los actores involucrados en la problemática abordada.',
    solution: 'Descripción de la solución propuesta por el equipo. Se detallarán las estrategias, métodos y tecnologías seleccionadas para resolver el problema planteado.',
    tools: ['Herramienta 1', 'Herramienta 2', 'Herramienta 3'],
    evidences: [
      { label: 'Presentación del equipo', href: '#', type: 'presentation' },
      { label: 'Informe técnico', href: '#', type: 'document' },
    ],
    reflection: 'Reflexión del equipo sobre los aprendizajes obtenidos, competencias desarrolladas y cómo este desafío impactó en nuestro crecimiento profesional y grupal.',
  },
  {
    slug: 'd5',
    code: 'D5',
    title: 'Desafío 5: [Título por completar]',
    problem: 'Descripción del problema o situación que motivó este desafío. Este apartado detallará el contexto, el alcance y los actores involucrados en la problemática abordada.',
    solution: 'Descripción de la solución propuesta por el equipo. Se detallarán las estrategias, métodos y tecnologías seleccionadas para resolver el problema planteado.',
    tools: ['Herramienta 1', 'Herramienta 2', 'Herramienta 3'],
    evidences: [
      { label: 'Presentación del equipo', href: '#', type: 'presentation' },
      { label: 'Informe técnico', href: '#', type: 'document' },
    ],
    reflection: 'Reflexión del equipo sobre los aprendizajes obtenidos, competencias desarrolladas y cómo este desafío impactó en nuestro crecimiento profesional y grupal.',
  },
  {
    slug: 'd6',
    code: 'D6',
    title: 'Desafío 6: [Título por completar]',
    problem: 'Descripción del problema o situación que motivó este desafío. Este apartado detallará el contexto, el alcance y los actores involucrados en la problemática abordada.',
    solution: 'Descripción de la solución propuesta por el equipo. Se detallarán las estrategias, métodos y tecnologías seleccionadas para resolver el problema planteado.',
    tools: ['Herramienta 1', 'Herramienta 2', 'Herramienta 3'],
    evidences: [
      { label: 'Presentación del equipo', href: '#', type: 'presentation' },
      { label: 'Informe técnico', href: '#', type: 'document' },
    ],
    reflection: 'Reflexión del equipo sobre los aprendizajes obtenidos, competencias desarrolladas y cómo este desafío impactó en nuestro crecimiento profesional y grupal.',
  },
  {
    slug: 'd7',
    code: 'D7',
    title: 'Desafío 7: [Título por completar]',
    problem: 'Descripción del problema o situación que motivó este desafío. Este apartado detallará el contexto, el alcance y los actores involucrados en la problemática abordada.',
    solution: 'Descripción de la solución propuesta por el equipo. Se detallarán las estrategias, métodos y tecnologías seleccionadas para resolver el problema planteado.',
    tools: ['Herramienta 1', 'Herramienta 2', 'Herramienta 3'],
    evidences: [
      { label: 'Presentación del equipo', href: '#', type: 'presentation' },
      { label: 'Informe técnico', href: '#', type: 'document' },
    ],
    reflection: 'Reflexión del equipo sobre los aprendizajes obtenidos, competencias desarrolladas y cómo este desafío impactó en nuestro crecimiento profesional y grupal.',
  },
];
